message: This is a message defined in the configuration file config.yaml.
messageRepetitions: 3
database:
   driverClass: com.mysql.jdbc.Driver
   user: awarner
   password: netscape
   url: jdbc:mysql://wolflakedb.c6gcrnwp3hea.us-west-2.rds.amazonaws.com/testdb
   maxWaitForConnection: 1s
  # the SQL query to run when validating a connection's liveness
   validationQuery: "/* MyService Health Check */ SELECT 1"
  # the minimum number of connections to keep open
   minSize: 8
  # the maximum number of connections to keep open
   maxSize: 32
  # whether or not idle connections should be validated
   checkConnectionWhileIdle: false
  # the amount of time to sleep between runs of the idle connection validation, abandoned cleaner and idle pool resizing
   evictionInterval: 10s
  # the minimum amount of time an connection must sit idle in the pool before it is eligible for eviction
   minIdleTime: 1 minute
logging:
   level: INFO
server:
  applicationConnectors:
  - type: http 
    port: 9000
  adminConnectors:
  - type: http
    port: 9001
   